apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - name: model
        image: nasermandal/sea_level_predictor:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: model-service
spec:
  type: NodePort
  selector:
    app: model
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
