apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor
        image: monitor-app:latest
        args: ["python", "monitor.py"]
        imagePullPolicy: Never

apiVersion: v1 # exposing monitoring
kind: Service
metadata:
  name: monitor-service
spec:
  type: NodePort
  selector:
    app: monitor
  ports:
    - port: 5001        #  exposed by the service
      targetPort: 5000  # exposed inside the container
      nodePort: 30002   
