name: BuildTestEvaluateModel

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Prod" ]

jobs:
  train-and-eval:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name:  Install dependencies
      run: |
        pip install pandas numpy scikit-learn

    - name: Train model (model.py)
      run: |
        python model.py

    - name:  Evaluate model (evaluate_model.py)
      run: |
        python evaluate_model.py

    - name:  (Optional) Build Docker image
      run: |
        docker build -t sea-level-predictor .
