name: BuildTestEvaluateModel

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Prod" ]

jobs:
  
  job1:
    name: training the model
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: setting up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: installing dependencies
      run: pip install pandas numpy scikit-learn

    - name: runnung the model.py and creating model.pkl
      run: python model.py
    
    - name: uploading model.pkl to be used in job2
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: model.pkl

  
  job2:
    name:  evaluating model by running evaluate_model.py
    runs-on: ubuntu-latest
    needs: job1-train-model

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: setting up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install pandas numpy scikit-learn

    - name: Download trained model
      uses: actions/download-artifact@v4
      with:
        name: trained-model
      run: python evaluate_model.py


  job3:
    name: Docker build for Image
    runs-on: ubuntu-latest
    needs: job2-evaluate-model

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: setting up docker build
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t sea-level-predictor .