name: Deploy to Prod

on:
  push:
    branches: [ "Prod" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: nasermandal
        password: dckr_pat_iFRiA1cnoYl0807IzY5o30bNiNc

    - name: Pull latest image from Docker Hub
      run: |
        docker pull nasermandal/sea_level_predictor:latest

    - name: Stop and remove old container (if any)
      run: |
        docker stop sea-level-app || true
        docker rm sea-level-app || true

    - name: Run live container
      run: |
        docker run -d -p 5000:5000 --name sea-level-app nasermandal/sea_level_predictor:latest
