name: Build and Push Monitor Image

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Prod" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name:  Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: nasermandal
        password: dckr_pat_iFRiA1cnoYl0807IzY5o30bNiNc

    - name: Build and push Docker image to Docker Hub
      run: |
        docker build -t nasermandal/monitor-app:latest ./minikube/monitor
        docker push nasermandal/monitor-app:latest
