name: Run Docker Image

on:
  workflow_dispatch:  # manually triggering from the github

jobs:
  run-docker:
    runs-on: ubuntu-latest
    #runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Building Docker image
      run: |
        docker build -t sea-level-predictor .

    - name: Runing Docker container
      run: |
        docker run -d -p 5000:5000 --name sea-level-app sea-level-predictor
        sleep 10  # giving time to the server to start

    - name: Test Flask endpoint
      run: |
        curl --fail http://localhost:5000 || (echo "Flask app not responding!" && exit 1)

    - name: stopping docker and removal of the container
      if: always()
      run: |
        docker stop sea-level-app
        docker rm sea-level-app